- package.json
- src/App.js
- src/App.test.js
- src/__snapshots__/App.test.js.snap
- src/pages/__snapshots__/aboutPage.spec.js.snap
- src/pages/__snapshots__/homePage.spec.js.snap
- src/pages/aboutPage.js
- src/pages/aboutPage.spec.js
- src/pages/homePage.js
- src/pages/homePage.spec.js
- yarn.lock
Added router as per trello card :
https://trello.com/c/4NSnFyfr/37-react-router-implement-react-router-on-core-codebase
> Added app basic router and snapshot test

- README.md
As suggested in standup 05/10/20
> Updated readme to explain how to deal with the react-scripts error

- src/components/Card.js
- src/components/Card.spec.js
- src/components/FeelingsSection.js
- src/components/FeelingsSection.spec.js
- src/components/HelpSection.js
- src/components/HelpSection.spec.js
- src/components/__snapshots__/Card.spec.js.snap
- src/components/__snapshots__/FeelingsSection.spec.js.snap
- src/components/__snapshots__/HelpSection.spec.js.snap
- src/pages/__snapshots__/homePage.spec.js.snap
- src/pages/homePage.spec.js
plus a typo fix in feelings section
> Learn more button links to the help page

- src/components/FlashCard.js
- src/components/FlashCard.spec.js
- src/components/FlashCardsSection.js
- src/components/__snapshots__/FlashCard.spec.js.snap
- src/pages/__snapshots__/helpPage.spec.js.snap
This Pr solves the following trello card: https://trello.com/c/sUDS7Hm2/60-store-user-choices-in-session
> Nadim 02 session storage

- manifest.yml
Update path in manifest.yml to fix the deployment
> Update path in manifest.yml

- README.md
- package-lock.json
- package.json
- src/server.ts
Covers ticket: https://trello.com/c/pH9hb2JX/59-update-readme-to-include-instructions-for-both-frontend-and-nodejs
> Local dev setup

- web-app/src/index.css
- web-app/src/pages/__snapshots__/helpPage.spec.js.snap
- web-app/src/pages/__snapshots__/homePage.spec.js.snap
- web-app/src/pages/helpPage.js
- web-app/src/pages/homePage.js
https://trello.com/c/XAK5SkQz/77-limit-space-on-page-to-1440-px
> limit page size

- nodemon.json
- package-lock.json
- package.json
https://trello.com/c/z4UGjdCR/96-add-nodemon-to-backend-libraries-to-hot-reload-code-changes
Commands to run local dev are not changed.
> add nodemon

- src/services/cos.service.spec.ts
- src/services/cos.service.ts
- src/services/help.service.spec.ts
- src/services/help.service.ts
- src/statics.ts
- src/types/Cos.ts
- src/util/cosCreds.ts
- web-app/src/components/FlashCard.js
- web-app/src/components/__snapshots__/FlashCard.spec.js.snap
Reverts lebanon-relief-project/LRP-web-app#53
> Revert "Cos fix"

- src/services/cos.service.spec.ts
- src/services/cos.service.ts
- src/services/help.service.spec.ts
- src/services/help.service.ts
- src/statics.ts
- src/types/Cos.ts
- src/util/cosCreds.ts
- web-app/src/components/FlashCard.js
- web-app/src/components/__snapshots__/FlashCard.spec.js.snap
Reverts lebanon-relief-project/LRP-web-app#54
> Revert "Revert "Cos fix""

- web-app/src/components/FlashCard.js
- web-app/src/components/FlashCard.spec.js
- web-app/src/components/__snapshots__/FlashCard.spec.js.snap
- web-app/src/util/deviceUtil.js
https://trello.com/c/Vsor7yAn/102-fix-flashcards
- Flashcard flipping is now on click for mobile, not on focus
- Flipped flashcard opacity is now 0.92 for readibility 
- Flashcard text has 8px padding on the left and right (https://www.figma.com/file/SfRqwuE3GEpM3RkgsH4VLC/Main?node-id=1212%3A0)
> Flashcard update

- web-app/src/components/FlashCard.js
Co-authored-by: matejocovskyibm <matej.ocovsky@ibm.com>
> Fixed card flipping bug on mobile

- src/controllers/index.ts
- src/controllers/percentage.controller.spec.ts
- src/controllers/percentage.controller.ts
- src/services/index.ts
- src/services/percentage.service.api.ts
- src/services/percentage.service.spec.ts
- src/services/percentage.service.ts
- src/statics.ts
- src/types/ExperiencePercentage.ts
- src/types/sampleData/PercentageSampleData.ts
Co-authored-by: matejocovskyibm <matej.ocovsky@ibm.com>
> Added Percentage API

- src/services/results.service.spec.ts
- src/services/results.service.ts
- web-app/src/components/FlashCard.js
- web-app/src/util/util.js
- web-app/src/util/util.spec.js
https://trello.com/c/cLd9pXvn/128-flashcards-should-remain-flipped-if-page-is-refreshed
https://trello.com/c/E3Qm3D4D/122-update-api-results-to-return-pre-signed-image-url-in-response
> Flashcard remain flipped

- web-app/src/components/Footer.js
- web-app/src/components/LikeToHelpModal.js
- web-app/src/components/__snapshots__/Footer.spec.js.snap
- web-app/src/components/__snapshots__/LikeToHelpModal.spec.js.snap
https://trello.com/c/z58fao17/124-change-all-emails-to-contactlebanonreliefnetworkorg
> change email address

- manifest.yml
- src/util/cosCreds.ts
https://trello.com/c/CWnDiyFb/132-add-static-cos-credentials-to-cf-and-pull-from-env
> pull cos credentials from env not VCAP_SERVICES

- web-app/src/components/resultsPage/FlashCardResultContainer.js
- web-app/src/components/resultsPage/__snapshots__/FlashCardResultContainer.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultsSection.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
https://trello.com/c/d4VRWXk4/125-add-logic-to-handle-more-than-5-flashcards-being-selected-scroll-list-etc
> add overflow property

- web-app/src/components/FlashCardsSection.spec.js
- web-app/src/components/FooterImageLink.spec.js
- web-app/src/components/__snapshots__/FooterImageLink.spec.js.snap
- web-app/src/pages/__snapshots__/helpPage.spec.js.snap
- web-app/src/pages/__snapshots__/homePage.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
- web-app/src/pages/aboutPage.spec.js
- web-app/src/pages/helpPage.spec.js
- web-app/src/pages/homePage.spec.js
- web-app/src/pages/resultsPage.spec.js
https://trello.com/c/8Dg5Zz04/133-fix-all-snapshot-tests-to-use-styled-components
> Snapshots fix

- web-app/src/components/resultsPage/ResultsSection.js
- web-app/src/components/resultsPage/ResultsSection.spec.js
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
- web-app/src/pages/resultsPage.js
- web-app/src/pages/resultsPage.spec.js
- web-app/src/services/results.service.js
https://trello.com/c/1Ay9EIn2/130-frontend-calls-results-api-with-ids-in-session-storage
> Results api integration

- web-app/src/components/FlashCardsSection.js
- web-app/src/components/__snapshots__/FlashCardsSection.spec.js.snap
https://trello.com/c/CbVAN4HD/143-give-me-advice-button-partially-not-working
> whole button can be used as a link

- web-app/src/components/resultsPage/FlashCardResultContainer.js
- web-app/src/components/resultsPage/FlashCardResultContainer.spec.js
- web-app/src/components/resultsPage/ResultsSection.spec.js
- web-app/src/components/resultsPage/__snapshots__/FlashCardResultContainer.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultsSection.spec.js.snap
https://trello.com/c/OCTgMVZy/144-get-flashcard-title-from-session-storage
> get flashcard result titles from session storage

- web-app/public/index.html
"Web site created using create-react-app"
->
"For a healthier, more trauma informed, and resilient Lebanon"
> Change site description

- web-app/src/pages/resultsPage.js
- web-app/src/pages/resultsPage.spec.js
https://trello.com/c/z2HSm8NZ/150-redirect-to-help-page-if-user-lands-on-results-page-with-no-cards-selected
> Redirect to help page if empty session storage

- src/statics.ts
- web-app/src/components/resultsPage/FlashCardResultContainer.js
- web-app/src/components/resultsPage/ResultCard.js
- web-app/src/components/resultsPage/__snapshots__/FlashCardResultContainer.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultCard.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultsSection.spec.js.snap
https://trello.com/c/kku3ogZO/151-display-flashcard-image-on-results-page
> display flashcard result image, title and body

- web-app/src/components/FlashCard.js
- web-app/src/components/__snapshots__/FlashCard.spec.js.snap
https://trello.com/c/28Y5A9o1/123-text-too-small-on-cards-from-mobile
> fix text size in cards on mobile

- web-app/src/components/TraumaticEventsSection.js
- web-app/src/components/__snapshots__/TraumaticEventsSection.spec.js.snap
- web-app/src/pages/__snapshots__/helpPage.spec.js.snap
https://trello.com/c/xBiLY7bm/140-replace-text-in-the-im-looking-for-help-page
> change text on the help page and fix mobile styling

- web-app/src/components/FeelingsSection.js
- web-app/src/components/__snapshots__/FeelingsSection.spec.js.snap
- web-app/src/pages/__snapshots__/helpPage.spec.js.snap
https://trello.com/c/xBiLY7bm/140-replace-text-in-the-im-looking-for-help-page
> changed text to match designs

- web-app/src/components/HelpSection.js
- web-app/src/components/LikeToHelpModal.js
- web-app/src/components/OurMissionSection.js
- web-app/src/components/WhatHappenedSection.js
- web-app/src/components/__snapshots__/HelpSection.spec.js.snap
- web-app/src/components/__snapshots__/LikeToHelpModal.spec.js.snap
- web-app/src/components/__snapshots__/OurMissionSection.spec.js.snap
- web-app/src/components/__snapshots__/WhatHappenedSection.spec.js.snap
https://trello.com/c/r3Sy8PJN/147-front-page-text-multiple-edits
https://trello.com/c/96V6bfUp/214-front-page-on-tablet-has-too-small-text-areas
> Front end text and tablet changes 

- web-app/src/components/FlashCard.js
- web-app/src/components/__snapshots__/FlashCard.spec.js.snap
https://trello.com/c/28Y5A9o1/123-text-too-small-on-cards-from-mobile
> fix text size on desktop for flashCards

- web-app/src/App.js
- web-app/src/components/Footer.js
- web-app/src/components/FooterLink.js
- web-app/src/components/__snapshots__/Footer.spec.js.snap
- web-app/src/components/__snapshots__/FooterLink.spec.js.snap
- web-app/src/pages/PrivacyPage.js
- web-app/src/pages/TermsPage.js
https://trello.com/c/VuAuzOzJ/216-privacy-policy-page
https://trello.com/c/86Zo8fVu/109-add-terms-of-use-page
> Privacy policy

- web-app/src/components/Navbar.js
- web-app/src/components/__snapshots__/Navbar.spec.js.snap
https://trello.com/c/nEK9gbmj/161-disable-id-like-to-help-from-navigation-menu
> disable id like to help navbar and add modal

- web-app/src/components/resultsPage/ExperiencesSection.js
- web-app/src/components/resultsPage/__snapshots__/ExperiencesSection.spec.js.snap
https://trello.com/c/30yQo1N9/164-text-after-percentage-in-results-page
> updated percentage text

- web-app/src/components/FlashCardsSection.js
- web-app/src/components/FlashCardsSection.spec.js
- web-app/src/components/NoCardSelectedModal.js
- web-app/src/components/NoCardSelectedModal.spec.js
- web-app/src/components/__snapshots__/FlashCardsSection.spec.js.snap
- web-app/src/components/__snapshots__/NoCardSelectedModal.spec.js.snap
https://trello.com/c/nEuOF7s6/131-handle-edge-case-of-user-going-to-results-page-without-selecting-any-cards
> Added modal when no cards selected

- web-app/src/components/resultsPage/ActionsSection.js
- web-app/src/components/resultsPage/ActionsSection.spec.js
- web-app/src/components/resultsPage/ReachOutModal.js
- web-app/src/components/resultsPage/ReachOutModal.spec.js
- web-app/src/components/resultsPage/__snapshots__/ReachOutModal.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
https://trello.com/c/GxhB3dsV/162-pop-up-when-clicking-reach-out-on-results-page
> Reach Out Modal

- web-app/src/components/HelpSection.js
https://trello.com/c/3kAdbtZ7/220-text-in-14-days-of-wellbeing-results-page
> updated text

- web-app/src/components/resultsPage/FlashCardResultContainer.js
- web-app/src/components/resultsPage/ResultCard.js
- web-app/src/components/resultsPage/__snapshots__/FlashCardResultContainer.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultCard.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultsSection.spec.js.snap
https://trello.com/c/0NwMbLqL/156-text-size-in-result-page-recommendations
> changed font size to match designs

- web-app/src/components/Footer.js
- web-app/src/components/FooterLink.js
- web-app/src/components/__snapshots__/Footer.spec.js.snap
- web-app/src/components/__snapshots__/FooterLink.spec.js.snap
https://trello.com/c/gitDXOCJ/146-add-code-contributions-link-to-git-hub
> Added code contribution link

- web-app/src/components/MobileNavBar.js
- web-app/src/components/Navbar.js
- web-app/src/components/__snapshots__/Navbar.spec.js.snap
https://trello.com/c/Dg4339KR/215-text-in-mobile-menu
> mobile menu styling

- web-app/src/components/resultsPage/ResultCard.js
- web-app/src/components/resultsPage/__snapshots__/FlashCardResultContainer.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultCard.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultsSection.spec.js.snap
https://trello.com/c/gYLR8QkJ/155-reduce-minimum-height-for-recommendations
> removed minimum height for the result cards component

- web-app/src/components/resultsPage/UsefulTipsSection.js
- web-app/src/components/resultsPage/__snapshots__/UsefulTipsSection.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
https://trello.com/c/RDqEquUS/223-image-of-the-girl-needs-to-be-offset-on-the-card
> image margin-left on results page

- web-app/src/components/Burger.js
- web-app/src/components/NoCardSelectedModal.js
- web-app/src/components/__snapshots__/Burger.spec.js.snap
- web-app/src/components/__snapshots__/MobileNavbar.spec.js.snap
https://trello.com/c/EIXeaetf/225-hamburger-needs-to-be-blue
Removed unused var
> Blue hamburger and removed unused var

- web-app/src/components/Card.js
- web-app/src/components/HelpSection.js
- web-app/src/components/__snapshots__/Card.spec.js.snap
- web-app/src/components/__snapshots__/HelpSection.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
https://trello.com/c/RreAjYtG/221-resize-bug-on-landing-page
> Fix wellbeing card resize bug

- web-app/src/components/resultsPage/ExperiencesSection.js
- web-app/src/components/resultsPage/__snapshots__/ExperiencesSection.spec.js.snap
https://trello.com/c/3kgr5a72/229-people-wrap-badly-on-some-mobiles-moto-g4-on-dev-tools
> Stop people symbol wraping on mobile

- web-app/src/components/HelpSection.js
- web-app/src/components/__snapshots__/HelpSection.spec.js.snap
- web-app/src/components/resultsPage/ActionsSection.js
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
https://trello.com/c/3kAdbtZ7/220-text-in-14-days-of-wellbeing-results-page
> fixed mistakes in the 14 days section

- web-app/src/components/LikeToHelpModal.js
- web-app/src/components/NoCardSelectedModal.js
- web-app/src/components/__snapshots__/LikeToHelpModal.spec.js.snap
- web-app/src/components/__snapshots__/NoCardSelectedModal.spec.js.snap
- web-app/src/components/resultsPage/ReachOutModal.js
- web-app/src/components/resultsPage/__snapshots__/ReachOutModal.spec.js.snap
https://trello.com/c/6cHVAR8Q/237-make-background-of-the-pages-not-clickable-when-the-modal-is-on
> fix issue where menu items are clickable when modal is active

- web-app/src/components/resultsPage/FlashCardResultContainer.js
- web-app/src/components/resultsPage/__snapshots__/FlashCardResultContainer.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultsSection.spec.js.snap
https://trello.com/c/4Foq1zvk/224-add-padding-to-text-on-results-page-paragraph
> Padding fix

- src/server.ts
https://trello.com/c/EynBEd0z/218-disable-http-route
> force https in non dev environment

- src/types/Challenge14Days.ts
- src/types/ConsentData.ts
- src/types/Psychotherapist.ts
Added psychotherapist, 14 Day Challenge and Consent Data types
> Added new types

- web-app/src/components/resultsPage/ActionsSection.js
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
PR: https://trello.com/c/gd01k6ip/227-lines-need-to-be-closer-to-the-text
> fix action text css

- src/controllers/results.controller.spec.ts
- src/controllers/results.controller.ts
- src/services/flashcard.service.api.ts
- src/services/flashcard.service.spec.ts
- src/services/flashcard.service.ts
- src/services/index.ts
- src/statics.ts
- src/types/FlashCard.ts
https://trello.com/c/SjB6KH28/129-store-card-selection-in-the-database
> Selection storage

- src/statics.ts
- web-app/src/components/ContactUsSection.js
- web-app/src/components/ContactUsSection.spec.js
- web-app/src/components/FlashCard.js
- web-app/src/components/FlashCardsSection.js
- web-app/src/components/__snapshots__/ContactUsSection.spec.js.snap
- web-app/src/components/__snapshots__/FlashCard.spec.js.snap
- web-app/src/components/__snapshots__/FlashCardsSection.spec.js.snap
- web-app/src/pages/__snapshots__/helpPage.spec.js.snap
- web-app/src/pages/helpPage.js
I've updated the flash cards page to match the designs on Figma
https://trello.com/c/dajRH4E0/241-changes-flashcards-page
> Updated Flash Cards Page

- web-app/src/components/FlashCard.js
- web-app/src/components/FlashCardsSection.js
remove unused imports to fix console warnings
> remove imports to fix console warnings

- package-lock.json
- web-app/package-lock.json
- web-app/src/components/ContactUsSection.js
- web-app/src/components/FeelingsSection.js
- web-app/src/components/FlashCard.js
- web-app/src/components/FlashCardsSection.js
- web-app/src/components/Footer.js
- web-app/src/components/FooterLink.js
- web-app/src/components/TraumaticEventsSection.js
- web-app/src/components/__snapshots__/ContactUsSection.spec.js.snap
- web-app/src/components/__snapshots__/FeelingsSection.spec.js.snap
- web-app/src/components/__snapshots__/FlashCard.spec.js.snap
- web-app/src/components/__snapshots__/FlashCardsSection.spec.js.snap
- web-app/src/components/__snapshots__/Footer.spec.js.snap
- web-app/src/components/__snapshots__/FooterLink.spec.js.snap
- web-app/src/components/__snapshots__/TraumaticEventsSection.spec.js.snap
- web-app/src/components/resultsPage/ActionsSection.js
- web-app/src/components/resultsPage/ExperiencesSection.js
- web-app/src/components/resultsPage/ResultsSection.js
- web-app/src/components/resultsPage/UsefulTipsSection.js
- web-app/src/components/resultsPage/__snapshots__/ActionsSection.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ExperiencesSection.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/ResultsSection.spec.js.snap
- web-app/src/components/resultsPage/__snapshots__/UsefulTipsSection.spec.js.snap
- web-app/src/pages/PrivacyPage.js
- web-app/src/pages/TermsPage.js
- web-app/src/pages/__snapshots__/helpPage.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
Applied fixes to the card page and the results page
> Centred the pages so content shouldn't be off to one side any more

- src/statics.ts
Added environment variables to the server which can override the hardcoded defaults.
Supported values can be found in `statics.ts`
> Database Environment Variables

- web-app/src/components/MobileNavBar.js
- web-app/src/components/Navbar.js
- web-app/src/components/__snapshots__/MobileNavbar.spec.js.snap
- web-app/src/components/__snapshots__/Navbar.spec.js.snap
https://trello.com/c/kfSXwvxC/239-navigation-bar-is-taller
> Set navbar height to 80px as in the designs

- web-app/src/components/Card.js
- web-app/src/components/HelpSection.js
- web-app/src/components/OurMissionSection.js
- web-app/src/components/WellbeingSection.js
- web-app/src/components/WhatHappenedSection.js
- web-app/src/components/__snapshots__/Card.spec.js.snap
- web-app/src/components/__snapshots__/HelpSection.spec.js.snap
- web-app/src/components/__snapshots__/OurMissionSection.spec.js.snap
- web-app/src/components/__snapshots__/WellbeingSection.spec.js.snap
- web-app/src/components/__snapshots__/WhatHappenedSection.spec.js.snap
- web-app/src/components/resultsPage/ExperiencesSection.js
- web-app/src/components/resultsPage/__snapshots__/ExperiencesSection.spec.js.snap
- web-app/src/pages/__snapshots__/homePage.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
- web-app/src/pages/homePage.js
- web-app/src/styles/GlobalStyles.js
https://trello.com/c/sPW4N2lH/275-landing-page-boxes-bugs-and-fixes
> address bugs

- web-app/src/components/Card.js
- web-app/src/components/__snapshots__/Card.spec.js.snap
- web-app/src/components/__snapshots__/WellbeingSection.spec.js.snap
- web-app/src/pages/__snapshots__/resultsPage.spec.js.snap
> min width on cards

- web-app/src/components/FeelingsSection.js
- web-app/src/components/TraumaticEventsSection.js
- web-app/src/components/__snapshots__/FeelingsSection.spec.js.snap
- web-app/src/components/__snapshots__/TraumaticEventsSection.spec.js.snap
- web-app/src/pages/__snapshots__/helpPage.spec.js.snap
https://trello.com/c/hqYA9L4m/278-flashcards-page-text-edits
> help page text edit

- web-app/src/components/resultsPage/ExperiencesSection.js
- web-app/src/components/resultsPage/__snapshots__/ExperiencesSection.spec.js.snap
https://trello.com/c/a8QpXmpa/289-visualisation-bug-on-mobile
> fix header

- web-app/src/components/aboutPage/AboutUsSection.js
- web-app/src/components/aboutPage/OurValuesSection.js
- web-app/src/components/aboutPage/__snapshots__/OurValuesSection.spec.js.snap
- web-app/src/pages/__snapshots__/aboutPage.spec.js.snap
https://trello.com/c/eOXW6Iza/288-add-space-before-our-values-in-about-us-page
> Fixed spacing for our values section

- web-app/src/components/WhatHappenedSection.js
- web-app/src/components/__snapshots__/WhatHappenedSection.spec.js.snap
https://trello.com/c/zN5rvJSt/298-landing-page-edits
> landing page tweaks

- web-app/src/App.js
- web-app/src/pages/directory/__snapshots__/directoryPage.spec.js.snap
- web-app/src/pages/directory/components/Banner.js
- web-app/src/pages/directory/components/Banner.spec.js
- web-app/src/pages/directory/components/__snapshots__/Banner.spec.js.snap
- web-app/src/pages/directory/directoryPage.js
- web-app/src/pages/directory/directoryPage.spec.js
https://trello.com/c/3DVubRPb/262-create-blue-banner-for-directory-page
> created directory page and added banner

- web-app/src/components/Navbar.js
- web-app/src/components/__snapshots__/Navbar.spec.js.snap
fixed small bug where the nav context wrapper would still affect clickability on the mobile screen
> fix chevron
